branches:
  only:
    - master

os: Visual Studio 2017

clone_depth: 1

install:
  - mkdir ext && cd ext
  - git clone --depth 1 git://github.com/objectcomputing/OpenDDS.git
  - git checkout tags/DDS-3.12 -b master
  - cd OpenDDS
  - call configure --no-tests
  - git apply C:\OpenDDSharp\Patches\ConditionImpl.h.patch
  - git apply C:\OpenDDSharp\Patches\DataReaderImpl.cpp.patch
  - git apply C:\OpenDDSharp\Patches\DataReaderImpl.h.patch
  - git apply C:\OpenDDSharp\Patches\unique_ptr.h.patch
  - cd ..
  - cd ..
  - set MPC_ROOT C:\ext\OpenDDS\ACE_wrappers\MPC
  - set ACE_ROOT C:\ext\OpenDDS\ACE_wrappers
  - set DDS_ROOT C:\ext\OpenDDS  
  - msbuild DDS_TAOv2.sln /m /p:Configuration=Debug;Platform=x64
  - msbuild DDS_TAOv2.sln /m /p:Configuration=Release;Platform=x64
  - xcopy C:\ext\OpenDDS\ACE_wrappers\lib E:\ext\OpenDDS\ACE_wrappers\lib_x64
  - xcopy C:\ext\OpenDDS\ACE_wrappers\bin E:\ext\OpenDDS\ACE_wrappers\bin_x64
  - xcopy C:\ext\OpenDDS\lib E:\ext\OpenDDS\lib_x64
  - xcopy C:\ext\OpenDDS\bin E:\ext\OpenDDS\bin_x64
  - msbuild DDS_TAOv2.sln /m /p:Configuration=Debug;Platform=Win32
  - msbuild DDS_TAOv2.sln /m /p:Configuration=Release;Platform=Win32
  - xcopy C:\ext\OpenDDS\ACE_wrappers\lib E:\ext\OpenDDS\ACE_wrappers\lib_x86
  - xcopy C:\ext\OpenDDS\ACE_wrappers\bin E:\ext\OpenDDS\ACE_wrappers\bin_86
  - xcopy C:\ext\OpenDDS\lib E:\ext\OpenDDS\lib_x86
  - xcopy C:\ext\OpenDDS\bin E:\ext\OpenDDS\bin_x86
  
platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

build_script:
  - msbuild OpenDDSharp\OpenDDSharp.sln /m /p:Configuration=Debug;Platform=x64
  - msbuild OpenDDSharp\OpenDDSharp.sln /m /p:Configuration=Release;Platform=x64
  - msbuild OpenDDSharp\OpenDDSharp.sln /m /p:Configuration=Debug;Platform=x86
  - msbuild OpenDDSharp\OpenDDSharp.sln /m /p:Configuration=Release;Platform=x64
  
  
