branches:
  only:
    - master

os: Visual Studio 2017

clone_depth: 1

install:
  - mkdir ext && cd ext
  - git clone git://github.com/objectcomputing/OpenDDS.git
  - cd OpenDDS
  - git fetch && git fetch --tags
  - git checkout tags/DDS-3.12 
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64  
  - ps: Start-FileDownload 'http://download.ociweb.com/TAO-2.2a/ACE+TAO-2.2a_with_latest_patches_NO_makefiles.zip'
  - 7z e ACE+TAO-2.2a_with_latest_patches_NO_makefiles.zip -aoa -oC:\projects\openddsharp\ext\OpenDDS
  - set MPC_ROOT C:\projects\openddsharp\ext\OpenDDS\ACE_wrappers\MPC
  - set ACE_ROOT C:\projects\openddsharp\ext\OpenDDS\ACE_wrappers
  - set DDS_ROOT C:\projects\openddsharp\ext\OpenDDS
  - call configure --no-tests    
  - git apply C:\projects\openddsharp\Patches\ConditionImpl.h.patch
  - git apply C:\projects\openddsharp\Patches\DataReaderImpl.cpp.patch
  - git apply C:\projects\openddsharp\Patches\DataReaderImpl.h.patch
  - git apply C:\projects\openddsharp\Patches\unique_ptr.h.patch
  - cd ..
  - cd .. 
  - msbuild DDS_TAOv2.sln /m /p:Configuration=Debug;Platform=x64
  - msbuild DDS_TAOv2.sln /m /p:Configuration=Release;Platform=x64
  - xcopy C:\ext\OpenDDS\ACE_wrappers\lib E:\ext\OpenDDS\ACE_wrappers\lib_x64
  - xcopy C:\ext\OpenDDS\ACE_wrappers\bin E:\ext\OpenDDS\ACE_wrappers\bin_x64
  - xcopy C:\ext\OpenDDS\lib E:\ext\OpenDDS\lib_x64
  - xcopy C:\ext\OpenDDS\bin E:\ext\OpenDDS\bin_x64
  - msbuild DDS_TAOv2.sln /m /p:Configuration=Debug;Platform=Win32
  - msbuild DDS_TAOv2.sln /m /p:Configuration=Release;Platform=Win32
  - xcopy C:\ext\OpenDDS\ACE_wrappers\lib E:\ext\OpenDDS\ACE_wrappers\lib_x86
  - xcopy C:\ext\OpenDDS\ACE_wrappers\bin E:\ext\OpenDDS\ACE_wrappers\bin_86
  - xcopy C:\ext\OpenDDS\lib E:\ext\OpenDDS\lib_x86
  - xcopy C:\ext\OpenDDS\bin E:\ext\OpenDDS\bin_x86
  
platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

build_script:
  - msbuild C:\projects\openddsharp\OpenDDSharp\OpenDDSharp.sln /m /p:Configuration=Debug;Platform=x64
  - msbuild C:\projects\openddsharp\OpenDDSharp\OpenDDSharp.sln /m /p:Configuration=Release;Platform=x64
  - msbuild C:\projects\openddsharp\OpenDDSharp\OpenDDSharp.sln /m /p:Configuration=Debug;Platform=x86
  - msbuild C:\projects\openddsharp\OpenDDSharp\OpenDDSharp.sln /m /p:Configuration=Release;Platform=x64
  
  
